---
- name: Ensure docker users are added to the docker group.
  become: true
  user:
    name: "{{ muser }}"
    groups: docker
    append: true
  loop_control:
    loop_var:  muser
  with_items: "{{ docker_users }}"

- name: Reset ssh connection to apply user changes.
  meta: reset_connection
